name: Build par2 for ARM64
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install cross-compilation tools
        run: |
          sudo apt update
          sudo apt install -y build-essential autoconf automake g++-aarch64-linux-gnu
      - name: Clone par2cmdline
        run: |
          git clone https://github.com/Parchive/par2cmdline.git
          cd par2cmdline
      - name: Configure and build
        run: |
          cd par2cmdline
          autoreconf -i
          ./configure --host=aarch64-linux-gnu LDFLAGS="-static" CFLAGS="-static"
          make
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: par2-arm64
          path: par2cmdline/par2
